#ifndef CORE_H
#define CORE_H

#include "systemc.h"
#include "pe.h"

SC_MODULE(Core)
{
    sc_in<bool> rst; // Active-low reset shared by the packet injection and ejection stages.
    sc_in<bool> clk; // Clock used by the Core network-interface threads.

    // Router-to-NI valid-ready link.
    sc_in<sc_lv<34>> flit_rx; // Incoming 34-bit flit from the router local output port.
    sc_in<bool> req_rx;       // Valid signal from the router; high when flit_rx carries a valid flit.
    sc_out<bool> ack_rx;      // Ready signal to the router; high when this core can accept a flit.

    // NI-to-router valid-ready link.
    sc_out<sc_lv<34>> flit_tx; // Outgoing 34-bit flit driven to the router local input port.
    sc_out<bool> req_tx;       // Valid signal to the router; high when flit_tx carries a valid flit.
    sc_in<bool> ack_tx;        // Ready signal from the router; high when the router can accept flit_tx.

    PE pe;       // Processing element that generates packets and checks received packets.
    int core_id; // Core/router ID in the 4x4 mesh, passed to the processing element.

    void init(int id)
    {
        core_id = id;
        pe.init(id);
    }

    // Drive one flit through the synchronous valid-ready link protocol.
    void send_flit(const sc_lv<34> &flit)
    {
        while (true)
        {
            if (rst.read() == 0)
            {
                req_tx.write(false);
                wait();
                continue;
            }

            flit_tx.write(flit);
            req_tx.write(true);
            wait();

            if (ack_tx.read() == 1)
            {
                req_tx.write(false);
                return;
            }
        }
    }

    // Packet injection stage: serialize one PE packet into header/body/tail flits.
    void tx_thread()
    {
        while (true)
        {
            if (rst.read() == 0)
            {
                sc_lv<34> zero_flit; // Idle flit value driven while reset keeps the TX link invalid.
                zero_flit = 0;
                req_tx.write(false);
                flit_tx.write(zero_flit);
                wait();
                continue;
            }

            Packet *packet = pe.get_packet(); // Packet generated by the PE for injection; NULL means no packet.
            if (packet == NULL)
            {
                wait();
                continue;
            }

            sc_lv<34> header; // Header flit: type, destination ID, and source ID.
            header.range(33, 32) = 2;
            header.range(31, 16) = packet->dest_id;
            header.range(15, 0) = packet->source_id;
            send_flit(header);

            for (size_t i = 0; i < packet->datas.size(); i++)
            {
                sc_lv<34> flit; // Body or tail flit carrying one 32-bit floating-point payload pattern.
                if (i == packet->datas.size() - 1)
                    flit.range(33, 32) = 1;
                else
                    flit.range(33, 32) = 0;

                union
                {
                    float fval;        // Payload value from the packet data vector.
                    unsigned int ival; // Bit-equivalent 32-bit integer stored in the flit payload.
                } converter;           // Converts between float data and raw 32-bit flit payload bits.

                converter.fval = packet->datas[i];
                flit.range(31, 0) = converter.ival;
                send_flit(flit);
            }

            delete packet;
        }
    }

    // Decode one accepted flit and update the packet currently being reconstructed.
    void receive_flit(const sc_lv<34> &flit, Packet &packet, bool &packet_active)
    {
        unsigned int type = flit.range(33, 32).to_uint(); // Two-bit flit type field.

        if (type == 2)
        {
            packet = Packet();
            packet.dest_id = flit.range(31, 16).to_uint();
            packet.source_id = flit.range(15, 0).to_uint();
            packet_active = true;
        }
        else if (packet_active && (type == 0 || type == 1))
        {
            union
            {
                float fval;        // Reconstructed floating-point payload value.
                unsigned int ival; // Raw 32-bit payload bits extracted from the flit.
            } converter;           // Converts raw flit payload bits back into a float.

            converter.ival = flit.range(31, 0).to_uint();
            packet.datas.push_back(converter.fval);

            if (type == 1)
            {
                pe.check_packet(&packet);
                packet_active = false;
                packet = Packet();
            }
        }
    }

    // Packet ejection stage: deserialize incoming flits accepted by valid-ready handshake.
    void rx_thread()
    {
        Packet packet;              // Packet currently being reconstructed from incoming flits.
        bool packet_active = false; // True after a header flit is received and before its tail flit arrives.

        while (true)
        {
            if (rst.read() == 0)
            {
                packet = Packet();
                packet_active = false;
                ack_rx.write(false);
                wait();
                continue;
            }

            ack_rx.write(true);

            if (req_rx.read() == 1)
                receive_flit(flit_rx.read(), packet, packet_active);

            wait();
        }
    }

    SC_HAS_PROCESS(Core);
    Core(sc_module_name name) : sc_module(name)
    {
        sc_lv<34> zero_flit; // Initial idle value for the TX flit signal.
        zero_flit = 0;

        req_tx.initialize(false);
        ack_rx.initialize(true);
        flit_tx.initialize(zero_flit);

        SC_THREAD(tx_thread);
        sensitive << clk.pos();
        SC_THREAD(rx_thread);
        sensitive << clk.pos();
    }
};

#endif
